name: deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -Dmaven.test.skip=true deploy -Dregistry=https://maven.pkg.github.com/wkgreat -Dtoken=dbfb6a3e55969ae7c4f6cc748709d6d759560a68
